### ISSUE TITLE
Feature request: crop writable area

### ISSUE THREAD

**Issue by jtgd** [resloved/xtext#1]
It might to useful to some to have xtext not write to the entire screen. I'm not sure how hard it would be, but it would be nice to simply specify a rectangle to constrain the area of the screen written to. 
Also perhaps `-bg color` for the background.

**Comment by resloved** [comment]
Thanks for the feedback! Didn't realize someone actually used this. 

Having the writable area surround only the text extents seems reasonable and an easy enough fix. Then you wouldn't even need a compositor to use xtext! For the background color you can just use the following pango syntax:

`<span background="#ff0000">test<span>`

**Comment by resloved** [comment]
As of 18a50948e2bdee5bbd633f91d4f898c3463775c2 xtext now resizes the window based on the size of the text and no longer draws over the entire screen.

If it works as intended for you please close the issue, otherwise let me know.

**Comment by jtgd** [comment]
Awesome! Thank you.
