### ISSUE TITLE
Add code for the helper functions

### ISSUE THREAD

**Issue by schrmh** [resloved/xtext#3]
Looks like it isn't inside the repo?
For example `grep -r rainbow`
```
grep: .git/index: Übereinstimmungen in Binärdatei
README.md:anim 'rainbow' | rainbow | xtext 0 0
README.md:  <img src="screenshots/rainbow.gif">
```

**Comment by resloved** [comment]
The helper functions aren't added to your path so they don't work out of the box even if you install via `AUR`. They are all in [examples/animation](https://github.com/resloved/xtext/tree/master/examples/animation)

**Comment by schrmh** [comment]
Ah, missed that. Thanks
